# Generated by Django 6.0.5 on 2026-05-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('qualification', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('Gadag', 'ಗದಗ')], max_length=100)),
                ('taluk', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='doctors/')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
