# Generated by Django 6.0.5 on 2026-05-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
