# Generated by Django 6.0.5 on 2026-05-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_village'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200, verbose_name='ಕಾಯಿಲೆಯ ಹೆಸರು')),
                ('treatment_details', models.TextField(verbose_name='ಪ್ರಥಮ ಚಿಕಿತ್ಸೆಯ ವಿವರಣೆ')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='YouTube ಲಿಂಕ್')),
                ('icon_class', models.CharField(default='bi-heart-pulse', max_length=50)),
            ],
        ),
    ]
