# Generated by Django 6.0.5 on 2026-05-09 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_doctor_latitude_doctor_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='longitude',
        ),
    ]
