# Generated by Django 6.0.5 on 2026-05-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_doctor_latitude_remove_doctor_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovtScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ಯೋಜನೆಯ ಹೆಸರು')),
                ('description', models.TextField(verbose_name='ಯೋಜನೆಯ ವಿವರ')),
                ('benefits', models.TextField(verbose_name='ಪ್ರಯೋಜನಗಳು')),
                ('eligibility', models.TextField(verbose_name='ಅರ್ಹತೆಗಳು (Eligibility)')),
                ('apply_link', models.URLField(blank=True, null=True, verbose_name='ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಲಿಂಕ್')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
