# Generated by Django 6.0.5 on 2026-05-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_review_user_review_farmer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstaid',
            name='dosage',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ಔಷಧಿಯ ಪ್ರಮಾಣ'),
        ),
        migrations.AddField(
            model_name='firstaid',
            name='medicines',
            field=models.TextField(blank=True, null=True, verbose_name='ಸೂಚಿಸಿದ ಔಷಧಿಗಳು'),
        ),
    ]
