# Generated by Django 6.0.5 on 2026-05-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_firstaid_dosage_firstaid_medicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstaid',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='firstaid',
            name='medicines',
        ),
    ]
