# Generated by Django 6.0.5 on 2026-05-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_firstaid_dosage_remove_firstaid_medicines'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='ಡಾಕ್ಟರ್ ಪ್ರಮಾಣಪತ್ರ'),
        ),
    ]
