# Generated by Django 6.0.5 on 2026-05-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_doctor_doctor_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='ಡಾಕ್ಟರ್ ಪ್ರಮಾಣಪತ್ರ'),
        ),
    ]
