# Generated by Django 6.0.5 on 2026-05-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_doctor_doctor_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_certificate',
            new_name='certificate',
        ),
    ]
