# Generated by Django 6.0.5 on 2026-05-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_doctor_certificate_doctor_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Doctor Certificate'),
        ),
    ]
