# Generated by Django 6.0.5 on 2026-05-30 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_doctor_latitude_doctor_longitude_doctor_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerted_at', models.DateTimeField(auto_now_add=True)),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.accidentreport')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
            ],
        ),
    ]
