# Generated by Django 6.0.5 on 2026-06-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alertlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='district',
            field=models.CharField(choices=[('Gadag', 'ಗದಗ'), ('Dharwad', 'ಧಾರವಾಡ')], max_length=100),
        ),
    ]
