# Generated by Django 6.0.5 on 2026-06-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_doctor_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='district',
            field=models.CharField(choices=[('Gadag', 'Gadag'), ('Dharwad', 'Dharwad')], max_length=100),
        ),
    ]
